### ISSUE TITLE
UUID generators

### ISSUE THREAD

**Issue by lucapette** [lucapette/fakedata#22]
As specified [here](https://en.wikipedia.org/wiki/Universally_unique_identifier). We can (should?) support the multiple versions available and follow the naming of the ip generators: `uuidv1`, `uuidv2` and so on.

For this generator, it may make sense to do some preliminary research to find a library we're comfortable with to add as a dependency.

**Comment by kevingimbel** [comment]
[satori/go.uuid](https://github.com/satori/go.uuid) seems to be the [most stared library for UUID generation in Go](https://golanglibs.com/top?q=uuid). It supports v1-v5 and seems to be rather "simple" to use. 

I'd give this a try, especially because of the many stars compared to other libs.

**Comment by lucapette** [comment]
@kevingimbel thank you for researching. I'll have some slack time in a week or so and can take care of it. But, as always, if you'd like to give it a try please go ahead :)

**Comment by kevingimbel** [comment]
@lucapette I'm currently quite occupied with work and moving to a new flat soon, so I think I'll pass this time. Once things calm down a bit I'd like to do one of the other generators. :)

**Comment by lucapette** [comment]
@kevingimbel ok, no worries! And good luck with the move. That's always hard!

**Comment by kevingimbel** [comment]
Thanks!

**Comment by bl-ue** [comment]
Wow, no progress since 2017? 👀

**Comment by lucapette** [comment]
We have uuidv1 and uuidv4 now. I'll cut a release soon to get them out and we'll improve from there
