### ISSUE TITLE
bash/zsh completion

### ISSUE THREAD

**Issue by lucapette** [lucapette/fakedata#25]
As `fakedata` is a CLI tool, auto-completion would make usage much more enjoyable. I suggest we provide an option that outputs the completion function. Something like:

```sh
$ fakedata --completion=bash
```

so that we can ask users to add `eval $(fakedata --completion)` (I'm not sure it's the best API, suggestions, as always, more than welcome).  

While doing some quick search around the topic I run into [complete](https://github.com/posener/complete) but I'm not sure it suits this use case yet.

**Comment by kevingimbel** [comment]
**Some resources:**
*Bash Completion Overview*: Intro on the topic and what't the behaviour https://debian-administration.org/article/316/An_introduction_to_bash_completion_part_1

*Bash Completion Implementation Details*: How to implement auto complete https://debian-administration.org/article/317/An_introduction_to_bash_completion_part_2

**Comment by kevingimbel** [comment]
I assigned myself because I started to fiddle around with a idea I've had.

**Comment by lucapette** [comment]
@kevingimbel 👍 awesome!

**Comment by kevingimbel** [comment]
Closing this issue because the feature was merged with PR #53
