### ISSUE TITLE
Update docs for enum to explain usage for fixed values

### ISSUE THREAD

**Issue by jorinvo** [lucapette/fakedata#29]
fakedata is working great so far! Thanks for creating it!
Just a  small thing to add:

I'm using it to generate some SQL. One column should be the same for all rows.
Right now I pass `id=int,12345..12345` to limit the range to only this number.
Would be nice if I could also just do `id=int,12345`.
Also, if I like to do the same thing for a string value, there is currently no way to do so, right?

**Comment by kevingimbel** [comment]
> Would be nice if I could also just do id=int,12345.
> Also, if I like to do the same thing for a string value, there is currently no way to do so, right?

So what you actually want is a fixed "repeat" generator? Where one value is repeated over and over again? 

At the moment you can fake this by using the `enum` generator similar to how you used the int generator: 

```sh
$ fakedata enum,string..string int,12345..12345
string 12345
string 12345
string 12345
string 12345
string 12345
string 12345
string 12345
string 12345
string 12345
string 12345
```

Could you work with the `enum` generator? Or would you suggest adding a fixed generator like `repeat` (`fakedata repeat,string repeat,12345`) which takes an argument and repeats it?

**Comment by jorinvo** [comment]
Thanks for pointing out enum! That's totally enough for strings I think.
No need for `repeat` in my opinion.
Surprisingly (haven't looked at any source code so far) `enum,mystring` works while `int,123` does not. So adding support for single values to `int` would be the only thing :)

**Comment by kevingimbel** [comment]
For the `int` generator a single argument is the min-value, so `int,123` works and creates values above 123.

You could use `enum` for numbers instead of `int` which gives the same result.

```sh
$ fakedata -f sql enum,122 enum,string --limit 2
INSERT INTO TABLE (enum,enum) VALUES ('122','string');
INSERT INTO TABLE (enum,enum) VALUES ('122','string');
# With column names
$ fakedata -f sql fixed_int=enum,122 fixed_string=enum,string --limit 2
INSERT INTO TABLE (fixed_int,fixed_string) VALUES ('122','string');
INSERT INTO TABLE (fixed_int,fixed_string) VALUES ('122','string');
```

```sh
$ fakedata -f sql int,122..122 enum,string --limit 2
INSERT INTO TABLE (int,enum) VALUES ('122','string');
INSERT INTO TABLE (int,enum) VALUES ('122','string');
```

Maybe it's more of a documentation thing then. If `enum` is able to handle fixed values this could be documented in the README as a feature for fixed, repeated columns.

What do you think @lucapette?

**Comment by jorinvo** [comment]
You're right @kevingimbel. Actually it's enough already. The generated value being a string is not a problem since SQL can still handle the INSERT.

As you suggest, improving the docs would "fix" this issue :)

**Comment by lucapette** [comment]
At some point I thought of adding a `const` or `repeat` generator but I agree it feels unneeded and the doc fix would do. Thank you so much for your contributions! They really help. I go ahead and merge the PR.
