### ISSUE TITLE
More top-level domain generators

### ISSUE THREAD

**Issue by kevingimbel** [lucapette/fakedata#33]
I think it makes sense to have more top-level domains added to the generator, especially the new once like `.codes`, `.academy`, `.website`, etc. 

Depending on what you're using the fakedata for it's good to have the diversity of the new, longer tlds. The old domain validation patterns (e.g. checking for length 2-4 characters) don't work on new tlds so having them in fakedata could provide a benefit when testing large datasets against an API or validation implementation.

**Comment by lucapette** [comment]
I agree! While I think we may want to use #30 in the long run, I don't think it's worth waiting for the discussion to happen. I can go ahead and take care of it if you want!

**Comment by kevingimbel** [comment]
I personally don't need this feature fast. If we can cover it in #30 that's good for me. 👍

**Comment by jorinvo** [comment]
https://data.iana.org/TLD/tlds-alpha-by-domain.txt

**Comment by lucapette** [comment]
@jorinvo thank you for the list. I'll bring it in. I'll comment in #30 how I'd like to proceed.

@kevingimbel I'll take care of it then :)

**Comment by gnanet** [comment]
@lucapette i have the project on watchlist, i get every change into my mailbox :)
