### ISSUE TITLE
Load a list of words from a file

### ISSUE THREAD

**Issue by lucapette** [lucapette/fakedata#34]
The discussion started [here](https://github.com/lucapette/fakedata/issues/30#issuecomment-303556059). Thanks to @gnanet to bring this up. 

The first approach that comes to mind is to use a small convention based on the name of the input file (without the extension) for the generator name, moreover I think it makes sense that this particular option is repeatable. For example:

```sh
$ echo "ciao\nhello" > file1.txt
$ fakedata --from-file=file1.txt -l=2 email file1
ciao xtopherpaul@test.us
hello plbabin@test.us
$
$ echo "priviet\nhallo" >file2.txt
$ fakedata --from-file=file2.txt --from-file=file1.txt -l=2 file1 file2 
ciao priviet
hello hallo
```

I like it! And it's a fun feature to build :) 

@gnagnet does this work for what you had in mind?

**Comment by gnanet** [comment]
this "from file" would represent an enum like solution, and the only problem i would see, is that we already have "reserved words" that may conflict, if i would use name.txt for example 

But this would work in my case for szinek.txt which in turn would contain color-names in hungarian, and varosok.txt for city names, but also i could have a rather long list of roomtypes, where i could simulate a lot of booking actions with a huge variation of roomtypes booked.

I am thrilled how much energy was released in short time. But i also see that i will need to read a lot of backlogs to catch up, if i cannot spend time day by day.

**Comment by jorinvo** [comment]
Why not but the `from-file` part into a generate instead of a flag?

> `$ fakedata --from-file=file2.txt --from-file=file1.txt -l=2 file1 file2`

would be

`$ fakedata -l=2 file,file1.txt file,file2.txt`

**Comment by lucapette** [comment]
@gnanet the only concern you have is valid but, and this is really **great**, I think @jorinvo's suggestion makes that go away.  If any of you would like to give this feature a try, please let me know and I assign it accordingly. Otherwise, it's the first feature on my personal list after #33. It's another awesome addition to fakedata! Thank you very much for participating in the discussion

**Comment by gnanet** [comment]
I support the solution of the **file** generator in this way.

But i have questions: what systems does fakedata build on currently? If we allow files, do we allow relative/absolute paths, or only same-location files? If we allow paths, we need to take care of space-containing paths or filenames?

**Comment by lucapette** [comment]
@gnanet right now we releases binaries for win/linux/macos 64 bit only (you can download/see the releases [here](https://github.com/lucapette/fakedata/releases/tag/v0.5.0)). As we don't really have a user base yet demanding for anything more specific I literally went for [goreleaser](https://github.com/goreleaser/goreleaser) defaults.

By default absolute paths + current directory sounds like a good starting point to me. As for the spaces, yes I think it makes sense to support them (although it can become annoying to write the code for it)

**Comment by jorinvo** [comment]
The Go standard library handles paths pretty well. Can support relative and absolute paths. If you have spaces in it, you can put the whole path in quotes:
`$ fakedata -l=2 file,'../mean dir/data/file1.txt`

**Comment by lucapette** [comment]
@jorinvo oh I didn't know it would support relative/absolute paths automatically. Good news (and it's obvious I'm still new to most parts of the standard library which makes this project even funnier to work with for me :))

**Comment by jorinvo** [comment]
@lucapette https://play.golang.org/p/ssfzhfvp2F

**Comment by gnanet** [comment]
I hoped for the answer of @jorinvo that with the right quoting, and the behaviour of the Go standard libs we will have no issues other than checking the exsistence, readability of the files, and maybe we will need to be prepared for the newline variants of the win/lin/mac (this is one thing why i was asking ;) )

**Comment by lucapette** [comment]
@gnanet the feature just landed on master so I'm going to close this issue. I'll be pushing a new release soon (I'd like to have #36 in too before I do). If you're not able to test the feature before I push a new release out (you can test it with go get) I can ping you when we release a new version
