### ISSUE TITLE
Support defining custom helpers in templates

### ISSUE THREAD

**Issue by gmile** [lucapette/fakedata#58]
### Proposal

It would immensely help to have an ability to define custom helpers in templates. Custom helpers could be used across the template by referencing the custom helper name anywhere in the template.

Helper specification:

* a helper definition would look like this:

  ```
  {{ define "my_helper" }}
  Any string including references to core helpers like {{ Int }} or {{ other_custom_helper }} defined earlier
  {{ end }}
  ```

* it would be defined directly in the template:

  ```
  {{ define "my_buddy" }}
    {{ NameFirst }} {{ NameLast }}
  {{ end }}
  Hello, {{ my_buddy }}!
  ```

* when rendered, the helper itself would resolve to an empty string: when custom helper is defined in a template file, and that template file is passed to `fakedata`, all symbols occupied by all custom helpers would shrink into empty strings after initial parsing / interpretation phase.

  Consider the following template:

  ```
  {{ define "my_buddy" }}
    {{ NameFirst }} {{ NameLast }}
  {{ end }}
  {{ define "the_phone_number" }}
    "+380{{ Enum "97" "63" "50" }}{{ range Loop 7 }}{{ Int 0 9 }}{{end}}"
  {{ end }}
  The phone number of my buddy {{ my_buddy }} is {{ the_phone_number }}.
  ```

  Passing it to `fakedata` via:

  ```
  cat template.tmpl | fakedata -l 1
  ```

  Would result in the following sample output:

  ```
  
  
  The phone number of my buddy Brock Ebonie is +380974567313.
  ```

  Note the two blank lines. I'd be great to have them removed as well, but I'm not sure if it's possible to do this correctly.

* it _might_ be better (but also probably harder) to have the custom functions defined in an external file, and have it loaded before executing a template:

  ```
  echo "My phone number is {{ the_phone_number }}." | fakedata -x my_functions.tmpl -l 1
  ```

### Motivation

I'm working on a template that is a 300 lines JSON document. It looks like this (reduced significantly, for brevity):

```json
{
  "person": {
    "contact_info": {
      "phone_number": "+380637274547"
    },
    "confident_persons": [
      {
        "contact_info": {
          "phone_number": "+380977557274"
        }
      },
      {
        "contact_info": {
          "phone_number": "+380503311437"
        }
      }
    ]
  }
}
```

For it, I've made the following template:

```
{
  "person": {
    "contact_info": {
      "phone_number": "+380{{ Enum "97" "63" "50" }}{{ range Loop 7 }}{{ Int 0 9 }}{{end}}"
    },
    "confident_persons": [
      {
        "contact_info": {
          "phone_number": "+380{{ Enum "97" "63" "50" }}{{ range Loop 7 }}{{ Int 0 9 }}{{end}}"
        }
      },
      {
        "contact_info": {
          "phone_number": "+380{{ Enum "97" "63" "50" }}{{ range Loop 7 }}{{ Int 0 9 }}{{end}}"
        }
      }
    ]
  }
}
```

Obviously there's a huge duplication going on here. By defining a custom helper function, this could be reduced significantly, to:

```
{{ define "ukrainian_phone" }}
+380{{ Enum "97" "63" "50" }}{{ range Loop 7 }}{{ Int 0 9 }}{{end}}
{{ end }}
{
  "person": {
    "contact_info": {
      "phone_number": "{{ ukrainian_phone }}"
    },
    "confident_persons": [
      {
        "contact_info": {
          "phone_number": "{{ ukrainian_phone }}"
        }
      },
      {
        "contact_info": {
          "phone_number": "{{ ukrainian_phone }}"
        }
      }
    ]
  }
}
```

**Comment by kevingimbel** [comment]
This is a good idea in my opinion. Generally speaking I believe custom functions / helpers will be helpful. I remember we had the same problem with Names because in Hungary the Name shema is `Lastname Firstname` compared to `Firstname Lastname`.

@lucapette What's your opinion here?

**Comment by lucapette** [comment]
First of all, @gmile thank you very much for such a detailed issue. This is really a great contribution already. 

I agree with @kevingimbel this is a good idea. As he said, it's not the first time this was requested but at the time of the first conversation we did not have templates yet so this bit went somehow lost.

I like the `define` syntax proposed but I'm not sure I'd like fakedata to support inline definitions. I do like (quite a lot actually) the idea of passing additional definitions as arguments and I'm not sure it's harder to implement this way. So, in short, I agree with @gmile that is indeed better doing it this way.

If anyone would like to give it a try, I'm happy to support with review, suggestions, and so on. Otherwise, I'll do some planning later this week so I can find the time to get to this feature on my own. It's a pretty nice addition!
