### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by KevinGimbel** [lucapette/fakedata#69]
`fakedata` may or may not have some issues working with Windows and the Windows file system (e.g. `file` generator) due to it being developed and tested on *nix only (MacOS, Linux).

As a first step we should run some basic tests on a Windows machine.

**TODO**
- [ ] Install `fakedata` on windows
- [ ] Test generators like `file` 
- [ ] document issues

**Comment by kevingimbel** [comment]
I've to postpone this to sometime in March. I'm too occupied at the moment.

**Comment by lucapette** [comment]
Closing this for now as I'm assuming @KevinGimbel isn't working on it. (Of course please feel free to re-open)
