### ISSUE TITLE
Enum Generator question

### ISSUE THREAD

**Issue by Pinako-Ana** [lucapette/fakedata#83]
Hello!
i follow the readme
i entered this command echo {{ Enum "100" "2020" "40040" }} | fakedata -l 50 > test.txt
But there is an error like this "template: template:1: expected :="
how to fix it?

**Comment by lucapette** [comment]
hey! thank you for using `fakedata`!

can you please try the following:

```sh
echo '{{ Enum "100" "2020" "40040" }}' | fakedata -l 5
40040
100
2020
100
2020
```

I think this is a sign I should add single quotes to the examples in the docs

**Comment by Pinako-Ana** [comment]
thanks!! have a good day!
